services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    env_file:
      - .env.app.prod
    volumes:
      - /data/horilla/staticfiles:/app/staticfiles
      - /data/horilla/media:/app/media
    depends_on:
      migrations:
        condition: service_completed_successfully
        required: true
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:8000"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.app.prod
    entrypoint: ["/app/run_migrations.sh"]