name: Build and Push Horilla

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '*'


jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get docker tag for Horilla image
        id: horilla
        run: |
          echo "IMAGE_TAG=$(awk -F '=' '/IMAGE_TAG/{print $2}' ./Dockerfile.prod)" >> $GITHUB_OUTPUT

      - name: Build and push Horilla
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: |
            ghcr.io/keitaroinc/horilla:${{ steps.horilla.outputs.IMAGE_TAG }}